src/Entity/Tag.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TagRepository")
 */
class Tag
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", length=10)
     * @Assert\NotBlank()
     */
    private $tag_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $sort;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="tag")
     */
    private $product;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTagId()
    {
        return $this->tag_id;
    }

    public function setTagId($tag_id): void
    {
        $this->tag_id = $tag_id;
    }

    public function getSort()
    {
        return $this->sort;
    }

    public function setSort($sort): void
    {
        $this->sort = $sort;
    }

    public function getProduct()
    {
        return $this->product;
    }

    public function setProduct($product): void
    {
        $this->product = $product;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email")
 */
class User implements UserInterface, \Serializable
{
    const IS_ACTIVE = 1;
    const IS_WAITING = 2;

    const ROLE_USER = 'ROLE_USER';
    const ROLE_ADMIN = 'ROLE_ADMIN';
    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60, unique=true, nullable=true)
     * @Assert\Length(min=2, max=60)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Assert\Length(min=10, max="50")
     * @Assert\NotBlank()
     */
    private $fullname;

    /**
     * @ORM\Column(type="string", unique=true, length=70)
     * @Assert\Length(min=5, max=100)
     * @Assert\NotBlank()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank()
     * @Assert\Length(min=5, max=100)
     */
    private $password;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $confirmationToken;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $roles;

    /**
     * @ORM\Column(type="string")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string")
     */
    private $updated_at;

    public function __construct()
    {
        $this->roles = self::ROLE_USER;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(?string $fullname): self
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getConfirmationToken()
    {
        return $this->confirmationToken;
    }

    public function setConfirmationToken($confirmationToken): void
    {
        $this->confirmationToken = $confirmationToken;
    }

    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function setCreatedAt($created_at): void
    {
        $this->created_at = $created_at;
    }

    public function getRoles()
    {
        return array($this->roles);
    }

    public function setRoles($roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function setUpdatedAt($updated_at): void
    {
        $this->updated_at = $updated_at;
    }

    public function serialize()
    {
        return serialize([
            $this->id,
            $this->username,
            $this->password
        ]);
    }

    public function unserialize($serialized)
    {
        list($this->id,
            $this->username,
            $this->password) = unserialize($serialized);
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {
    }
}

templates/admin-base.html.twig
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Admin!{% endblock %}</title>

    {% block stylesheets %}
        <link href="{{ asset('css/admin/sb-admin.css') }}" rel="stylesheet">
        <link href="{{ asset('css/admin/dataTables.bootstrap4.css') }}" rel="stylesheet">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
              integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
              crossorigin="anonymous">
    {% endblock %}

</head>

<body id="page-top">

<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="/admin">Админка магазина</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>


</nav>

<div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="/">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Вернуться в магазин</span>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-folder"></i>
                <span>Магазин</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                <h6 class="dropdown-header">Главное</h6>
                <a class="dropdown-item" href="{{ path('all_users') }}">Пользователи</a>
                <a class="dropdown-item" href="{{ path('view_all_products') }}">Товары</a>
                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header">Второстепенное:</h6>
                <a class="dropdown-item" href="{{ path('view_all_tags') }}">Метки</a>
                <a class="dropdown-item" href="{{ path('view_all_categories') }}">Категории</a>
            </div>
        </li>
    </ul>

    <div id="content-wrapper">

        <div class="container-fluid">
            {% block body %}
            {% endblock %}
        </div>

        <!-- Sticky Footer -->
        <footer class="sticky-footer">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright © Your Website 2019</span>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->

{% block javascripts %}
    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('js/admin/jquery/jquery.easing.min.js') }}"></script>
    <script src="{{ asset('js/admin/chart.js/Chart.min.js') }}"></script>
    <script src="{{ asset('js/admin/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('js/admin/datatables/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ asset('js/admin/sb-admin.min.js') }}"></script>
    <script src="{{ asset('js/admin/datatables-demo.js') }}"></script>
    <script src="{{ asset('js/admin/chart-area-demo.js') }}"></script>
{% endblock %}

</body>

</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="megakassa" content="291c7b7c5b9" />

        <title>{% block title %}Добро пожаловать{% endblock %}</title>

        {% block stylesheets %}
            <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
            <link href="{{ asset('css/main.css') }}" rel="stylesheet">
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
                  integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
                  crossorigin="anonymous">
            <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.1/jquery.min.js"></script>
        {% endblock %}
    </head>
    <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/">Магазин</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    {% if app.user %}
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_login') }}">Вход</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('user_register') }}">Регистриция</a>
                    </li>
                    {% endif %}


                    {% if app.user %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ app.user.fullname }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if app.user %}
                            <a class="dropdown-item" href="{{ path('user_cabinet', {'id':app.user.id}) }}"><i class="fas fa-user"></i> {{ app.user.fullname }}</a>
                                <a class="dropdown-item" href="{{ path('main_basket_page', {'id':app.user.id}) }}"><i class="fas fa-shopping-basket"></i> Корзина</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ path('security_logout') }}"><i class="fas fa-sign-out-alt"></i> Выход</a>
                            {% else %}
                            {% endif %}
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block body %}
        <div class="container">
            <div class="row">

            </div>
        </div>
    {% endblock %}

    <footer class="py-4 bg-dark" id="footer">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
        </div>
    </footer>

    {% block javascripts %}
        <script src="{{ asset('js/jquery.min.js') }}"></script>
        <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
    {% endblock %}

    </body>
</html>

templates/cabinet.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-3">
        <div class="row">
            <dl class="row">
                <dt class="col-sm-3">Имя</dt>
                <dd class="col-sm-9">{{ user.fullname }}</dd>

                <dt class="col-sm-3">Ник</dt>
                <dd class="col-sm-9">
                    <p>{{ user.username }}</p>
                </dd>
                <dt class="col-sm-3">Email</dt>
                <dd class="col-sm-9">{{ user.email }}</dd>
                <dt class="col-sm-3">Дата регистриции</dt>
                <dd class="col-sm-9">{{ user.createdAt|date("m/d/Y") }}</dd>
            </dl>
        </div>


        <div class="card shopping-cart">
            <div class="card-body" id="divProduct">

                <!-- PRODUCT -->
                {% for item in items %}
                <div class="row mb-3">

                    <div class="col-12 col-sm-12 col-md-2 text-center">
                        <a href="{{ path('show_one_product', {'id':item.product.id}) }}">
                            <img class="img-responsive"
                                 src="{{ asset('upload/product/' ~ item.product.id|getPhoto(item.product.id)) }}"
                                 alt="prewiew" width="120" height="80">
                        </a>
                    </div>
                    <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                        <h4 class="product-name">
                            <a href="{{ path('show_one_product', {'id':item.product.id}) }}" style="color: black;">
                                <b>
                                    {{ item.product.id|getProduct(item.product.id).title }}
                                </b>
                            </a>
                        </h4>
                        <h4>
                            <small>{{ item.product.id|getProduct(item.product.id).description|slice(0, 100) }}</small>
                        </h4>
                    </div>
                    <p>Трек: {{ item.id|trackNumber(item.id).track }}
                        <br>
                        Дата оформления закза: {{ item.id|trackNumber(item.id).createdAt|date("m/d/Y") }}
                    </p>
                    <p></p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    </div>
    </div>

{% endblock %}

templates/main-page.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <!-- Search form -->
    <div class="input-group my-4 col-8 mx-auto">
        <input class="form-control py-2 border-right-0 border" type="search" placeholder="Найти..."
               id="example-search-input">
        <span class="input-group-append">
        <button class="btn btn-outline-primary rounded-right" type="button">
            <i class="fas fa-search"></i>
        </button>
    </span>
    </div>

    <!-- Products -->
    <div class="container">
        <div class="row">
            <div class="col">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        {% if path is defined %}
                        <li class="breadcrumb-item"><a href="{{ path('homepage') }}">Главная</a></li>
                        {% for category in path %}
                            {% if path|length != loop.index %}
                                <li class="breadcrumb-item"><a href="{{ path('search_by_category', {'id':category.id}) }}">{{ category.title }}</a></li>
                            {% else %}
                                <li class="breadcrumb-item active" aria-current="page">{{ category.title }}</li>
                            {% endif %}
                        {% endfor %}
                            {% else %}
                                <li class="breadcrumb-item active" aria-current="page">Главная</li>
                        {% endif %}
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    {% macro recursiveCategory(category) %}
        {% import _self as self %}
            <li class="list-group-item"><a href="{{ path('search_by_category', {'id':category.id}) }}">{{ category.lvl|srtRepeat(category.lvl) }}{{ category.title }}</a></li>
            {% if category.__children|length %}
                {% for child in category.__children %}
                        {{ self.recursiveCategory(child) }}
                    {% endfor %}
            {% endif %}
    {% endmacro %}

    {% from _self import recursiveCategory %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-3">
                <div class="card bg-light mb-3">
                    <div class="card-header bg-primary text-white text-uppercase"><i class="fa fa-list"></i> Категории
                    </div>

                    {% for category in categories %}
                        {{ recursiveCategory(category) }}
                    {% endfor %}
                </div>
            </div>
            <div class="col">
                <div class="row">
                    {% for product in products  %}
                    <div class="col-12 col-md-6 col-lg-4 mb-3">
                        <div class="card">
                            <img class="card-img-top" src="{{ asset('upload/product/' ~ product.photo.current.name) }}"
                                 alt="Card image cap">
                            <div class="card-body">
                                <h4 class="card-title"><a href="{{ path('show_one_product', {'id':product.id}) }}" title="View Product">{{ product.title }}</a>
                                </h4>
                                <p class="card-text">{{ product.description|length > 50 ? product.description|slice(0, 50) ~ '...' : product.description }}</p>
                                <div class="buy d-flex justify-content-between align-items-center">
                                    <div class="price text-success">
                                        <h5 class="mt-1">
                                        {% if product.id|minPrice == product.id|maxPrice %}
                                            {{ product.id|minPrice }}
                                            <b id="price">
                                                ₽
                                            </b>
                                        {% else %}
                                            {{ product.id|minPrice }}
                                            - {{ product.id|maxPrice }}
                                            <b id="price">
                                                ₽
                                            </b>
                                        {% endif %}
                                        </h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="BasketModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Корзина</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Этот товар успешно добавлен в корзину
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>

    <br>
    <br>
    <br>


{% endblock %}

templates/one-product.html.twig
{% extends 'main-page.html.twig' %}

{% block body %}
    <!-- Search form -->
    <div class="input-group my-4 col-8 mx-auto">
        <input class="form-control py-2 border-right-0 border" type="search" placeholder="Найти..."
               id="example-search-input">
        <span class="input-group-append">
        <button class="btn btn-outline-primary rounded-right" type="button">
            <i class="fas fa-search"></i>
        </button>
    </span>
    </div>

    <!-- nav with categories -->
    <div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ path('homepage') }}">Главная</a></li>
                    {% for category in path %}
                        {% if path|length != loop.index %}
                            <li class="breadcrumb-item"><a href="{{ path('search_by_category', {'id':category.id}) }}">{{ category.title }}</a></li>
                            {% else %}
                                <li class="breadcrumb-item active" aria-current="page">{{ category.title }}</li>
                        {% endif %}
                    {% endfor %}
                </ol>
            </nav>
        </div>
    </div>

    <!-- Page Content -->
    <div class="container">

    </div>
        <!-- Portfolio Item Heading -->
        <h3 class="">{{ product.title }}</h3>
        {% for onetag in product.tag %}
            <a href="{{ path('search_by_tag', {'id': onetag.tagId}) }}"><span class="badge badge-info">{{ onetag.tagId|getTag(onetag.tagId) }}</span></a>
        {% endfor %}

        <!-- Portfolio Item Row -->
        <div class="row">

            <div class="col-md-8">
{#                <img class="img-fluid" src="http://placehold.it/500x400" alt="">#}
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for photo in photos %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ photo.id-1 }}" class="active"></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="{{ asset('upload/product/' ~ photos[0].name) }}" style="width:400px; height: 500px">
                        </div>
                        {% for photo in photos %}
                            {% if loop.index == 1 %}
                            {% else %}
                            <div class="carousel-item">
                                <img class="d-block w-100" src="{{ asset('upload/product/' ~ photo.name) }}" style="width:400px; height: 500px">
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

            <div class="col-md-4" id="divProduct">
                <h3>Описание</h3>
                <p class="mt-2">{{ product.description }}</p>
                <div class="form-group">
                    <label for="sel1">Выбрать модификацию:</label>
                    <select class="form-control" id="choice">
                        {% for choice in choices %}
                        <option value="{{ choice.price }}">{{ choice.content }}</option>
                        {% endfor %}
                    </select>
                </div>
                <input type="button" class="btn btn-secondary btn-sm" value="+" onClick="change('amount',1,100, 1);"/>
                <input id="amount" type="text" value="1" style="width:35px;" quantity="1"/>
                <input type="button" class="btn btn-secondary btn-sm" value="-" onClick="change('amount',1,100,-1);"/>
                <div class="buy d-flex justify-content-between align-items-center">
{#                    <div class="price text-success"><h5 class="mt-4">Цена  {{ product.price }} ₽</h5></div>#}
                    <div class="price text-success"><h5 class="mt-4">Цена <b id="price">₽</b> </h5></div>
                    {% if app.user %}
                    <a href="#" class="btn btn-danger mt-3" onclick="addToBasketIntermediate('amount', {{app.user.id}}, {{ app.request.get('id') }})"><i class="fas fa-shopping-cart"></i> В корзину</a>
                    {% else %}
                        <a href="#" class="btn btn-danger mt-3" onclick="addToBasketIntermediate('amount', null, {{ app.request.get('id') }})"><i class="fas fa-shopping-cart"></i> В корзину</a>

                    {% endif %}
                    <a href="#" class="btn btn-success mt-3"><i class="fas fa-money-bill-alt"></i> Купить</a>
                </div>
            </div>
        </div>


        <!-- Modal -->
        <div class="modal fade" id="BasketModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Корзина</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Этот товар успешно добавлен в корзину
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    </div>
                </div>
            </div>
        </div>


        <h3 class="mt-4">Характеристики: </h3>
        <div class="row mt-1">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <thead>
                    </thead>
                    <tbody>
                    {% for modification in product.modification %}
                    <tr>
                        <td>{{ modification.title }}</td>
                        <td>{{ modification.text }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <!-- /.container -->
    <br>
    <br>
    <br>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(function(){
            $('#choice').change(function(){
                price = $('#choice :selected').val();
                var productPrice = document.getElementById("price");
                productPrice.innerText = price+" ₽";
                $('#price').attr('value',price)
            })
        });
    </script>

    <script>
        function change(objName, min, max, step) {
            var obj = document.getElementById(objName);
            var tmp = +obj.value + step;
            if (tmp<min) tmp=min;
            if (tmp>max) tmp=max;
            obj.value = tmp;
            obj.setAttribute('quantity', obj.value)
        }

        function addToBasketIntermediate(objName, userId, productId) {
            var obj = document.getElementById(objName);
            var objPrice = document.getElementById('price');

            var quantity = obj.getAttribute('quantity');
            var productPrice = objPrice.getAttribute('value');

            that = $(this);
            var url = "/basket/"+quantity+"/"+productPrice+"/"+userId+"/"+productId;

            if (userId == null) {
                alert("Вам нужно зарегистрироваться");
                return;
            }
            if (objPrice.getAttribute('value') == null) {
                alert("Выберите модификацию");
                return;
            }

            $.ajax({
                url: url,
                type: "POST",
                dataType: "json",
                data: {
                    "data": "some_var_value"
                },
                async: true,
                success: function () {
                    $("#divProduct").load(" #divProduct > *");
                    $('#BasketModal').modal('show')
                }
            });
            return false;
        }

    </script>

{% endblock %}